version: "3.3"

services:
  #service 1 - custom-image
  app-laravel-store:
    build:
      args:
        user: odenilson
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: odenilson/app-store
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: always
    networks:
      - net-store

  #service 2 - ngixn
  ngixn:
    image: nginx:alpine
    restart: always
    ports:
      - 8383:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - net-store

  #service 3 - mysql
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3367:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-store

  #service 4 - redis
  redis:
    image: redis:latest
    networks:
      - net-store

networks:
  net-store:
    driver: bridge